### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by GeoffWilliams** [GeoffWilliams/ncedit#8]
Latest PE 2019.1.0 gives an SSL error:

```shell
[root@pe-puppet /]# /opt/puppetlabs/puppet/bin/ncedit classes --group-name 'PE Master' --class-name puppet_enterprise::profile::master --param-name r10k_remote --param-value "https://github.com/GeoffWilliams/r10k-control"
Classifier signs of life detected, proceeding to classify...
SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure
```

We can debug this to get a stacktrace:

```
[root@pe-puppet /]# /opt/puppetlabs/puppet/bin/ncedit classes --group-name 'PE Master' --class-name puppet_enterprise::profile::master --param-name r10k_remote --param-value "https://github.com/GeoffWilliams/r10k-control" --verbosity debug
unknown argument '--verbosity'
[root@pe-puppet /]# /opt/puppetlabs/puppet/bin/ncedit --verbosity debug classes --group-name 'PE Master' --class-name puppet_enterprise::profile::master --param-name r10k_remote --param-value "https://github.com/GeoffWilliams/r10k-control"  
Classifier signs of life detected, proceeding to classify...
SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure
SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
/opt/puppetlabs/puppet/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/net/http.rb:981:in `connect'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/puppetclassify-0.1.7/lib/puppet_https.rb:83:in `make_ssl_request'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/puppetclassify-0.1.7/lib/puppet_https.rb:102:in `get'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/puppetclassify-0.1.7/lib/puppetclassify/groups.rb:22:in `get_group_id'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/ncedit-0.4.0/lib/ncedit/cmd.rb:83:in `nc_group_id'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/ncedit-0.4.0/lib/ncedit/cmd.rb:111:in `nc_group'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/ncedit-0.4.0/lib/ncedit/cmd.rb:460:in `classes'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/ncedit-0.4.0/exe/ncedit:74:in `block (3 levels) in <top (required)>'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/escort-0.4.0/lib/escort/app.rb:68:in `execute_action'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/escort-0.4.0/lib/escort/app.rb:55:in `execute'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/escort-0.4.0/lib/escort/app.rb:6:in `create'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/ncedit-0.4.0/exe/ncedit:14:in `<top (required)>'
/opt/puppetlabs/puppet/bin/ncedit:23:in `load'
/opt/puppetlabs/puppet/bin/ncedit:23:in `<main>'
Escort app failed to execute successfully, due to unknown error
```

This lands us in the `puppetclassify` gem which sure enough has a recently released version already :beers:  - fix will be an updated `ncedit` depending on this newer version.

**Comment by GeoffWilliams** [comment]
fix released in 0.4.1
